name = "Keeli Company Auxillary Mod"
author = "DartRuffian"
prefix = "BNA_KC"
mainprefix = "BNA"

[version]
path = "addons/core/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "kc_logo.paa",
    # "LICENSE",
    "README.md"
]
exclude = [
    "*.spp",
    "*.spp.painter_lock",
    "*.psd"
]

[properties]
author = "DartRuffian"
url = "https://github.com/DartRuffian/KeeliCompanyAux"

[hemtt.launch.default]
workshop = [
    "450814997" # CBA
]
presets = []
dlc = []
optionals = []
parameters = []

[hemtt.launch.previews]
workshop = [
    "450814997" # CBA
]
presets = []
dlc = []
optionals = []
parameters = [
    "C:\\Users\\skull\\OneDrive\\Documents\\Arma 3 - Other Profiles\\Previews\\missions\\Previews.VR\\mission.sqm",
    "-name=Previews"
]